### ISSUE TITLE
Videos are gone after container restart

### ISSUE THREAD

**Issue by kgnfth** [sooros5132/yt-dlp-web#1]
Hi thanks for the great work. I love it!

I am running yt-dlp-web from container, when i download a tiktok video for example the file is saved at `/downloads` folder, and its visible in the web ui until i restart the container the videos are gone in web ui.

Unfortunate i dont have exprience in JS otherwise i had implemented a database and send pr :(

**Comment by sooros5132** [comment]
Hello. Thank you for your feedback. :)

There was a Postgres database in the initial development of this project, but it was deleted because it was considered a waste of resources to use the database simply to store video lists.
Currently, the video list is simply saved as a file in the `/cache` path along with the memory cache.

Since Docker image version 0.1.2, the `cache` folder in `/downloads` has been separated into the `/cache` path. So you need to set `/cache` folder in `docker-compose.yml`.
If you do not have this setting, if you run `docker compose down`, the `/cache` folder will be deleted and the video list will be initialized.

To fix this, I think you need to upgrade to the latest(0.1.4) image and set `- /path/to/cache:/cache` in the `volumes` setting of `docker-compose.yml` file.

If you encounter the same problem, I would appreciate it if you could write a comment.

**Comment by kgnfth** [comment]
Yes! it works if i set the cache volume. Thank you very much!
